# Generated by Django 4.2.3 on 2024-01-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_weatherdata_air_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='date',
            field=models.DateTimeField(default='%Y/%m/%d-%H:%M'),
        ),
    ]
